### ISSUE TITLE
[ Feature Request ]  Relay-like pagination 

### ISSUE THREAD

**Issue by azzamsa** [heyrict/cindy-next-rust#5]
Hi,

I saw ` Relay-like pagination (not included)` is planned on the `Feature Roadmap`. Any plan to make this happen?

I am building a GraphQL server in Rust using async-graphql and having a hard time doing relay-like pagination. The only resource I found is:
- [https://github.com/vectordotdev/vector/blob/master/src/api/schema/relay.rs#L105](https://github.com/vectordotdev/vector/blob/master/src/api/schema/relay.rs?rgh-link-date=2022-02-21T09%3A17%3A48Z#L105) and [vector.dev/blog/graphql-api/#take-it-for-a-spin-in-the-vector-playground](https://vector.dev/blog/graphql-api/#take-it-for-a-spin-in-the-vector-playground)

If this repo supports `Relay-like pagination`, We will have more resources to follow.

Thanks.

**Comment by heyrict** [comment]
Thank you for your feature request.

Well, the short answer is no. I used relay-styled pagination around 4 years ago for this website, but switched to limit-offset style a while later for simplicity. I have no plan to switch back to relay in the near future.

If I remember correct, I added this line to roadmap because I thought it was possible to implement relay-style pagination **to diesel** with some minor modifications, as I managed to solved dynamic query (passed from `async-graphql`)  in this project, which is quite a complex problem.

As you said there are little resources to follow, I can give you some ideas about how to implement it.
Rust is a low level language and implementing [relay specifications](https://relay.dev/graphql/connections.htm#sec-Pagination-algorithm) is up to yourself. One approach is to translate `first` and `last` to `select ... limit {first} order by {order_field} {asc/desc}` in sql, and `before` and `after` to something like `... where {order_field} > {after} order by {order_field} {asc/desc}`. If you follow my code, you can change the query parameters in `src/gql_schema/*.rs` to achieve that, but any backend/ORM that support dynamic query can do the trick. `before` and `after` can be encoded as `{query_name}:{order_field_value}` or whatever unique token you like.
Another approach is to use [built-in cursor in postgresql](https://www.postgresql.org/docs/9.2/plpgsql-cursors.html), but I am not familiar with that and cannot give you advice about it.

Going to close this issue.

**Comment by azzamsa** [comment]
I have implemented the feature here https://github.com/async-graphql/async-graphql/issues/563#issuecomment-1060073851, Thanks a lot for the input, Would you like to add any suggestions for improvement?
